#This script deletes the files generated in all languages other than english

import os, sys, re
# Open a file
path = "C:/Users/hytirogd/Desktop/Archive/SEMIC 8/Maintenance of Core Vocabularies/Re3gistry/For Dimitris/For Dimitris/Updating on 24-04-2017/Registry files 26-4"
#use code below if you want to be prompted for path. The filepath given must be the folder containin all the files generated by the registry tool
#path = (input("Give path of the files: ")) 

dirs = os.listdir( path )

regexp = re.compile(r'..*.html')
regexpe = re.compile(r'.*en.html')

# This would print all the files and directories
for file in dirs:
	print file
	if regexp.search(file) is not None:
		print("matched -> "+file)
	elif file <> "cn.var":
   		subdirs = os.listdir(path+"/"+file)
   		for subfile in subdirs:
   			if regexpe.search(subfile) is not None:
   				print subfile
   			elif regexp.search(subfile) is not None:
   				os.remove(path+"/"+file+"/"+subfile)

   #path="C:/Users/hytirogd/Desktop/Archive/SEMIC 8/Maintenance of Core Vocabularies/corevocs/corevocs/"+file+"/cn.var"
   #print(path)
   #cnvor = open(path,"w")

   #cnvor.write("URI: {0}.en.html\n".format(file))
   #cnvor.write("Content-language: en,en-GB,en-US,en-AU,en-NZ; q=1.0\n")
   #cnvor.write("Content-type: text/html; q=1.0")

   #cnvor.close()
