#This script fixes the content of the cn.var files and the redirection of the "version 1" links which is wrong by default as generated by the registry tool

import os, sys

# Open a file
path = "C:/Users/hytirogd/Desktop/Archive/SEMIC 8/Maintenance of Core Vocabularies/Re3gistry/For Dimitris/For Dimitris/Updating on 24-04-2017/Registry files 26-4"
#use code below if you want to be prompted for path. The filepath given must be the folder containin all the files generated by the registry tool
#path = (input("Give path of the files: ")) 

dirs = os.listdir( path )

# This would print all the files and directories
for file in dirs:
   #print file
  if (file != "cn.var") & (file != "m8g.en.html"):
   path="C:/Users/hytirogd/Desktop/Archive/SEMIC 8/Maintenance of Core Vocabularies/Re3gistry/For Dimitris/For Dimitris/Updating on 24-04-2017/Registry files 26-4/"+file+"/cn.var"
   #If you use the prompt to input the path, change the line above to path = path+"/"+file+"/cn.var"
   print(path)
   cnvor = open(path,"w")

   cnvor.write("URI: {0}.en.html\n".format(file))
   cnvor.write("Content-language: en,en-GB,en-US,en-AU,en-NZ; q=1.0\n")
   cnvor.write("Content-type: text/html; q=1.0")

   cnvor.close()

#Same as before but for the "1" version folder
for file in dirs:
   #print file
  if (file != "cn.var") & (file != "m8g.en.html"):
   path="C:/Users/hytirogd/Desktop/Archive/SEMIC 8/Maintenance of Core Vocabularies/Re3gistry/For Dimitris/For Dimitris/Updating on 24-04-2017/Registry files 26-4/"+file+"/1/cn.var"
   #If you use the prompt to input the path, change the line above to path = path+"/"+file+"/1/cn.var"
   print(path)
   cnvor = open(path,"w")

   cnvor.write("URI: {0}.en.html\n".format(file))
   cnvor.write("Content-language: en,en-GB,en-US,en-AU,en-NZ; q=1.0\n")
   cnvor.write("Content-type: text/html; q=1.0")

   cnvor.close()